# Mod options
mod_name=CompostBag
mod_id=compostbag
group=dev.dhyces.compostbag
authors=Dhyces
version=4.1.0

at_enabled=true
common_mixin_enabled=false
fabric_mixin_enabled=true
neoforge_mixin_enabled=false

# Publishing
publish_debug = true
publish_type = release
modrinth_project_id = O0yMYEEZ
curseforge_project_id = 597828

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false