modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
modId="compostbag" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Compost Bag" #mandatory
#displayURL=" "
logoFile=" " #optional
credits=" " #optional
authors="dhyces" #optional
description='''
Adds a bag that composts items like the composter and works like the bundle
'''