import org.groovymc.modsdotgroovy.gradle.tasks.AbstractGatherPlatformDetailsTask

plugins {
    id 'idea'
    id 'java'
    id 'eclipse'
    id 'maven-publish'
    id 'org.groovymc.modsdotgroovy'
    id 'dev.architectury.loom'
}

base {
    archivesName = "${mod_name}-Neo-${minecraft_version}"
}

loom {
    neoForge {
        accessTransformer(project.file('src/main/resources/META-INF/accesstransformer.cfg'))
    }
    runs {
        client {
            client()
            setConfigName("Neo Client")
            ideConfigGenerated(true)
            runDir("run")
        }
        server {
            server()
            setConfigName("Neo Server")
            ideConfigGenerated(true)
            runDir("runServer")
        }
    }
}

sourceSets.main.resources.srcDir 'src/generated/resources'

repositories {
    mavenLocal()
    maven {
        name = 'Neo'
        url = 'https://maven.neoforged.net/releases'
    }
    maven {
        name 'Maven for PR #794' // https://github.com/neoforged/NeoForge/pull/794
        url 'https://prmaven.neoforged.net/NeoForge/pr794'
        content {
            includeModule('net.neoforged', 'testframework')
            includeModule('net.neoforged', 'neoforge')
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    neoForge "net.neoforged:neoforge:${neo_version}"
    mappings loom.layered() {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-1.20.4:2024.02.25@zip")
    }

    compileOnly project(":Common")
}

tasks.withType(JavaCompile).configureEach {
    source(project(":Common").sourceSets.main.allSource)
}
tasks.withType(Javadoc).configureEach {
    source(project(":Common").sourceSets.main.allJava)
}
tasks.named("sourcesJar", Jar) {
    from(project(":Common").sourceSets.main.allSource)
}

processResources {
    from project(":Common").sourceSets.main.resources
    filesMatching("neoforge.mods.toml") {
        copySpec()
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId project.group
            artifactId project.archivesBaseName
            version project.version
            artifact jar
        }
    }
    repositories {
        maven {
            url "file://" + System.getenv("local_maven")
        }
    }
}

modsDotGroovy {
    platform = org.groovymc.modsdotgroovy.types.core.Platform.NEOFORGE
    inferGather.set false
    gather {
        projectProperty("loader_version_range")
        projectProperty("neo_version_range")
    }
    multiplatform {
        from ':Common'
    }
    apply()
}

tasks.named('gatherNeoForgePlatformDetails', AbstractGatherPlatformDetailsTask).configure {
    minecraftVersion = '24w13a'
    platformVersion = '20.5.0-alpha.24w13a.20240328.230204'
}